async(page)=>{
 await page.route('http://127.0.0.1:4173/**',r=>r.continue());await page.setViewportSize({width:390,height:1100});
 const results=[],errors=[],writes=[],slugs=['mos-kebab','clean-cut','am-waldrand','gassert','kimberger','kompass-umzuege','rubi','sml-spitzer','durmus-gebaeudereinigung','watson-angelika-coach'];
 const err=e=>errors.push({url:page.url(),message:e.message}),req=r=>{if(!['GET','HEAD'].includes(r.method()))writes.push(r.url())};page.on('pageerror',err);page.on('request',req);
 const goto=p=>page.goto('http://127.0.0.1:4173/'+p,{waitUntil:'networkidle'}),assert=(v,m)=>{if(!v)throw Error(m)},run=async(name,fn)=>{try{await fn();results.push({name,pass:true})}catch(e){results.push({name,pass:false,error:e.message})}};
 await goto('rubi/');await page.evaluate(slugs=>{slugs.forEach(s=>sessionStorage.removeItem('tw-workflow-v1:'+s));sessionStorage.removeItem('tw-wow-kompass')},slugs);
 const finishBranch=async(slug,inspect)=>{
  await page.locator('.wf-quickfill button').click();const form=page.locator('form').filter({has:page.locator('.wf-quickfill')});await form.locator('button[type=submit]').click();await page.locator('[data-flow-handoff]').waitFor({state:'visible',timeout:5000});
  const record=await page.evaluate(s=>DemoFlow.latest(s),slug);inspect(record);
  await page.locator('[data-flow-handoff] a').first().click();await page.waitForLoadState('networkidle');assert((await page.locator('.branch-case').innerText()).includes(record.id),'Vorgang fehlt im Betrieb');
  if(['am-waldrand','sml-spitzer'].includes(slug)){await page.locator('[data-branch-plan] button[type=submit]').click();assert(await page.locator('[data-branch-error]').isVisible(),'Zu kleine Ressource zugelassen');await page.locator('#branch-resource').selectOption({index:1});}
  await page.locator('[data-branch-plan] button[type=submit]').click();await page.locator('[data-branch-finish]').waitFor({state:'visible',timeout:4000});for(const c of await page.locator('[name=check]').all())await c.check();await page.locator('#branch-note').fill('Beispiel: Wünsche aus dem neuen Einstieg abgestimmt.');await page.locator('[data-branch-finish] button[type=submit]').click();
  await page.locator('.branch-case > a').click();await page.waitForLoadState('networkidle');await page.reload({waitUntil:'networkidle'});const saved=await page.evaluate(s=>DemoFlow.latest(s),slug);assert(saved.status==='done','Abschluss fehlt nach Neuladen');inspect(saved);assert((await page.locator('[data-wf-customer]').innerText()).includes('Wünsche aus dem neuen Einstieg'),'Kundenrückmeldung fehlt');
 };
 await run('MOS: verschiedene Zutatenvarianten bis Küchenbon und Abholung',async()=>{
  await goto('mos-kebab/');await page.locator('[data-kebap-ingredient][value=zwiebel]').uncheck();assert(await page.locator('[data-kebap-layer=zwiebel]').evaluate(e=>e.classList.contains('omitted')),'Zwiebelschicht unverändert');await page.locator('[data-kebap-add]').click();await page.locator('[data-kebap-ingredient][value=sauce]').uncheck();await page.locator('[data-kebap-add]').click();await page.locator('[data-kebap-add]').click();
  assert(await page.evaluate(()=>MosWowCart.add(['<script>bad</script>']))===false,'Unzulässige Zutat akzeptiert');await page.locator('[data-kebap-checkout]').click();assert(await page.locator('[data-warenkorb-liste] li').count()===2,'Varianten zusammengefasst');await page.locator('[data-warenkorb-abschliessen]').click();await page.locator('[data-flow-slots] .slot-pille').first().click();await page.locator('[name=flow-name]').fill('Demo');await page.locator('[name=flow-telefon]').fill('01512345678');await page.locator('#bestell-wunsch').fill('Bitte beide Varianten getrennt verpacken.');await page.locator('[data-flow-weiter]').click();const r=await page.evaluate(()=>DemoFlow.latest('mos-kebab'));assert(r.items.length===2&&r.total===22.5,'Varianten/Summe falsch');assert(r.items.some(i=>i.quantity===2&&i.name.includes('Zwiebeln, Sauce')),'Zutaten oder Menge fehlen');await page.locator('[data-flow-handoff] a').first().click();await page.waitForLoadState('networkidle');assert((await page.locator('.wf-ticket').innerText()).includes('Zwiebeln, Sauce'),'Variante fehlt im Küchenbon');await page.locator('[data-next=cooking]').click();await page.locator('[data-next=ready]').click();await page.locator('.wf-ticket .wf-link').click();await page.waitForLoadState('networkidle');assert((await page.locator('[data-wf-customer]').innerText()).includes('Abholbereit'),'Abholstatus fehlt');
 });
 await run('Clean Cut: Style, Team und Dauer bis zum gebuchten Termin',async()=>{
  await goto('clean-cut/');for(const service of ['Bartpflege','Haarschnitt','Schnitt & Bart']){await page.locator('[data-cut-service]').filter({hasText:service}).last().click();await page.locator('[data-cut-photo]').evaluate(i=>i.decode());}
  await page.locator('[data-cut-team=lena]').focus();await page.keyboard.press('Enter');await page.locator('[data-cut-cta]').click();await page.waitForLoadState('networkidle');assert(await page.locator('[name=leistung]:checked').inputValue()==='Schnitt & Bart','Leistung fehlt');assert(await page.locator('[data-stylist=lena]').getAttribute('aria-pressed')==='true','Team fehlt im Kalender');assert((await page.locator('[name=friseur]:checked').inputValue()).startsWith('Lena'),'Team fehlt in Zusammenfassung');await page.locator('[data-day=Donnerstag]').click();await page.locator('[data-time="11:00"]').click();await page.locator('#vorname').fill('Demo');await page.locator('#nachname').fill('Beispiel');await page.locator('#handy').fill('01512345678');await page.locator('[data-slot][aria-pressed]:not([aria-disabled=true])').first().click();await page.locator('[data-confirm]').click();await page.locator('[data-flow-handoff]').waitFor({state:'visible',timeout:4000});const r=await page.evaluate(()=>DemoFlow.latest('clean-cut'));assert(r.duration===60&&r.stylist==='lena'&&r.leistung==='Schnitt & Bart','Termindaten falsch');await page.locator('[data-flow-handoff] a').first().click();await page.waitForLoadState('networkidle');assert(await page.locator('[data-booking="'+r.id+'"]').isVisible(),'Termin nicht im Teamkalender');await goto('clean-cut/vorgang.html?id='+r.id);assert((await page.locator('[data-wf-customer]').innerText()).includes('Schnitt & Bart'),'Kundentermin fehlt');
 });
 await run('Am Waldrand: Bike-Reiseidee, Zimmer und Zeitraum bis zum Aufenthalt',async()=>{
  await goto('am-waldrand/');for(const mood of ['wandern','ruhe','bike']){await page.locator('[data-forest-mood='+mood+']').click();await page.locator('[data-forest-photo]').evaluate(i=>i.decode());}
  await page.locator('[data-forest-plan]').click();await page.locator('[data-mappe-zimmer=doppelzimmer]').click();await page.locator('[data-planer-anreise]').fill('2027-04-10');await page.locator('[data-planer-abreise]').fill('2027-04-12');await page.locator('[data-planer-abreise]').dispatchEvent('change');assert((await page.locator('[data-planer-cta]').getAttribute('href')).includes('reiseidee=bike'),'Reiseidee fehlt am Link');await page.locator('[data-planer-cta]').click();await page.waitForLoadState('networkidle');assert((await page.locator('#nachricht').inputValue()).includes('Bike-Aufenthalt'),'Reiseidee fehlt im Formular');await finishBranch('am-waldrand',r=>{assert(r.data.zimmer==='doppelzimmer'&&r.data.abreise==='2027-04-12','Aufenthalt falsch');assert(r.data.nachricht.includes('Bike-Aufenthalt')&&r.data.nachricht.includes('Stellplatz'),'Wünsche verloren');});
 });
 await run('Gassert: zwei Favoriten vergleichen, Grenze und konkretes Fahrzeug anfragen',async()=>{
  await goto('gassert/');await page.locator('[data-motor-add]').click();await page.locator('[data-motor-car=fahrzeug-2]').click();await page.locator('[data-motor-add]').click();assert(await page.locator('[data-motor-table] table').count()===1,'Vergleich fehlt');await page.locator('[data-motor-car=fahrzeug-3]').click();await page.locator('[data-motor-add]').click();assert((await page.locator('[data-motor-status]').innerText()).includes('voll'),'Dritter Favorit nicht begrenzt');await page.locator('[data-motor-table] a').last().click();await page.waitForLoadState('networkidle');assert(await page.locator('#probefahrt-fahrzeug').inputValue()==='fahrzeug-2','Fahrzeug nicht übernommen');await finishBranch('gassert',r=>assert(r.data['probefahrt-fahrzeug']==='fahrzeug-2'&&r.data.anliegen==='probefahrt','Fahrzeug fehlt im Vorgang'));
 });
 await run('Kimberger: fünf Behandlungen und drei Stationen bis zum Termin',async()=>{
  await goto('kimberger/');for(const treatment of ['sensibelchen','klassik','klassik-plus','komfort','anti-aging']){await page.locator('[data-care-treatment='+treatment+']').click();assert((await page.locator('[data-care-photo]').getAttribute('src')).includes(treatment),'Behandlungsfoto falsch');await page.locator('[data-care-photo]').evaluate(i=>i.decode());}for(const step of ['0','2','1'])await page.locator('[data-care-step="'+step+'"]').click();await page.locator('[data-care-cta]').click();await page.waitForLoadState('networkidle');assert(await page.locator('[name=behandlung]:checked').inputValue()==='anti-aging','Behandlung fehlt');await finishBranch('kimberger',r=>assert(r.data.behandlung==='anti-aging','Behandlung fehlt im Termin'));
 });
 await run('Kompass: Route, Datum und mehrere Hilfen bleiben lokal bis zur Disposition',async()=>{
  await goto('kompass-umzuege/');const origin='Mosbach <img src=x onerror=window.routeInjected=true>';await page.locator('[data-route-from]').fill(origin);await page.locator('[data-route-to]').fill('Heidelberg · Beispiel');await page.locator('[data-route-date]').fill('2020-01-01');await page.locator('[data-route-form] button').click();assert(page.url().endsWith('kompass-umzuege/'),'Vergangenes Datum akzeptiert');await page.locator('[data-route-date]').fill('2027-04-16');await page.locator('[data-route-extra][value=packservice]').check();await page.locator('[data-route-extra][value=einlagerung]').check();await page.locator('[data-route-extra][value=moebelmontage]').check();assert(await page.locator('[data-route-stops] li').count()===5,'Etappen unverändert');assert(!await page.evaluate(()=>window.routeInjected),'Route als HTML ausgeführt');await page.locator('[data-route-form] button').click();await page.waitForLoadState('networkidle');assert(!page.url().includes('Mosbach')&&!page.url().includes('Heidelberg'),'Adressen in URL');assert(await page.locator('#von').inputValue()===origin,'Start verändert');assert(await page.locator('[name=zusatzleistung]:checked').count()===3,'Mehrere Hilfen verloren');await finishBranch('kompass-umzuege',r=>assert(r.data.von===origin&&r.data.zusatzleistung.length===3&&r.data.datum==='2027-04-16','Umzug unvollständig'));await goto('kompass-umzuege/betrieb.html');await page.locator('[data-wf-reset]').click();await page.waitForLoadState('networkidle');assert(await page.evaluate(()=>sessionStorage.getItem('tw-wow-kompass'))===null,'Routenentwurf nach Reset erhalten');
 });
 await run('Rubi: drei Aufgaben und Objektart gemeinsam bis zum Abschluss',async()=>{
  await goto('rubi/');await page.locator('[data-house-cta]').focus();await page.keyboard.press('Enter');assert((await page.locator('[data-house-error]').innerText()).includes('mindestens'),'Leere Auswahl nicht erklärt');for(const task of ['renovierung','garten','reparatur'])await page.locator('[data-house-task='+task+']').click();await page.locator('[data-house-object=gewerblich]').click();assert(await page.locator('[data-house-area].active').count()===3,'Hausbereiche nicht markiert');await page.locator('[data-house-cta]').click();await page.waitForLoadState('networkidle');assert(await page.locator('[name=objektarbeiten]:checked').count()===3,'Mehrfachauswahl nicht übertragen');await finishBranch('rubi',r=>assert(r.data.objektarbeiten.length===3&&r.data.objektart==='gewerblich','Objektauftrag unvollständig'));
 });
 await run('SML: vier Umzugsgrößen, Keller und obere Volumengrenze bis Disposition',async()=>{
  await goto('sml-spitzer/');for(const [size,count]of [['1-zimmer',1],['2-zimmer',2],['3-zimmer',3],['4-plus',4]]){await page.locator('[data-load-size="'+size+'"]').click();assert(await page.locator('[data-load-level]:not([hidden])').count()===count,'Ladebild reagiert nicht');}await page.locator('[data-load-cellar]').check();assert(await page.locator('[data-load-volume]').innerText()==='40–55 m³','Keller falsch berechnet');await page.locator('[data-load-cta]').click();await page.waitForLoadState('networkidle');assert(await page.locator('#branch-volume').inputValue()==='55','Volumen fehlt');await finishBranch('sml-spitzer',r=>assert(r.data.volumen==='55'&&r.data.keller==='ja'&&r.data.groesse==='4-plus','Ladebedarf fehlt'));
 });
 await run('Durmus: Abzieher mit Tastatur und Reinigungsbedarf bis zur Einsatzserie',async()=>{
  await goto('durmus-gebaeudereinigung/');await page.locator('#glass-clarity').focus();await page.keyboard.press('End');assert(await page.locator('#glass-clarity').inputValue()==='100','Abzieher per Tastatur nicht bedienbar');await page.keyboard.press('Home');assert(await page.locator('[data-glass-window]').evaluate(e=>e.style.getPropertyValue('--clear'))==='0%','Glasfläche nicht synchron');await page.locator('[data-glass-area]').fill('0');await page.locator('[data-glass-cta]').click();assert(page.url().endsWith('durmus-gebaeudereinigung/'),'Ungültige Fläche zugelassen');await page.locator('[data-glass-area]').fill('450');await page.locator('[data-glass-frequency]').selectOption('taeglich');assert(await page.locator('[data-glass-system]').innerText()==='System Premium','Bedarf falsch eingeordnet');await page.locator('[data-glass-cta]').click();await page.waitForLoadState('networkidle');assert(await page.locator('[name=leistung]:checked').inputValue()==='glasreinigung','Glasreinigung fehlt');await finishBranch('durmus-gebaeudereinigung',r=>assert(r.data.flaeche==='450'&&r.data.frequenz==='taeglich'&&r.data.leistung==='glasreinigung','Einsatzbedarf fehlt'));
 });
 await run('Watson: sechs Themen, Sortierung, freiwilliger Gesprächseinstieg bis zum Kennenlernen',async()=>{
  await goto('watson-angelika-coach/');for(const key of ['entscheidung','neustart','kraft','selbstvertrauen','klarheit','ziel']){await page.locator('[data-mind-topic='+key+']').click();assert(await page.locator('[data-mind-thoughts]').evaluate(e=>e.classList.contains('sorted')),'Gedanken nicht sortiert');}await page.locator('[data-mind-take]').uncheck();assert(!(await page.locator('[data-mind-cta]').getAttribute('href')).includes('impuls'),'Abgewählter Impuls bleibt');await page.locator('[data-mind-reset]').click();assert(await page.locator('[data-mind-topic][aria-pressed=true]').count()===0,'Reset unvollständig');await page.locator('[data-mind-topic=entscheidung]').click();await page.locator('[data-mind-take]').check();const question=await page.locator('[data-mind-question]').innerText();await page.locator('[data-mind-cta]').click();await page.waitForLoadState('networkidle');assert((await page.locator('#nachricht').inputValue()).includes(question),'Gesprächseinstieg fehlt');await finishBranch('watson-angelika-coach',r=>assert(r.data.thema==='entscheidung'&&r.data.nachricht.includes(question),'Gespräch nicht erhalten'));
 });
 await run('Reduzierte Bewegung: alle zehn neuen Einstiege ohne Animation',async()=>{await page.emulateMedia({reducedMotion:'reduce'});for(const slug of slugs){await goto(slug+'/');assert(await page.locator('.tw-experience').evaluate(e=>e.getAnimations({subtree:true}).length)===0,'Animation aktiv: '+slug);}await page.emulateMedia({reducedMotion:'no-preference'});});
 page.off('pageerror',err);page.off('request',req);return{results,errors,writes};
}
